import React from 'react';
import { ProcessedSlot } from '@/lib/parser';
import ProcessSlotCard from './ProcessSlotCard';

interface TimetablePrintViewProps {
    slots: ProcessedSlot[];
    day: string;
    room?: string;
    mode: 'student' | 'teacher' | 'room';
    date?: string;
    filters: any;
    generatedAt: string;
}

export default function TimetablePrintView({ slots, day, room, mode, date, filters, generatedAt }: TimetablePrintViewProps) {
    let selectionInfo = "";
    if (mode === 'student') {
        selectionInfo = `${filters.program || ''} ${filters.semester || ''} ${filters.section || ''}`.trim();
        if (filters.course) selectionInfo += ` (${filters.course})`;
    } else if (mode === 'teacher') {
        selectionInfo = filters.teacherName || "";
        if (filters.course) selectionInfo += ` (${filters.course})`;
    } else if (mode === 'room') {
        selectionInfo = filters.roomNumber || "";
    }

    return (
        <div id="timetable-print-view" className="w-[1220px] bg-white p-10 font-sans text-slate-800">
            {/* Header */}
            <div className="flex justify-between items-center mb-8 pb-5 border-b-2 border-slate-200">
                <div>
                    <div className="text-3xl font-black text-slate-700 tracking-tight">
                        Lucid <span className="text-violet-600">Timetable</span>
                    </div>
                    <div className="text-[11px] text-slate-400 font-semibold mt-1">
                        Generated by Lucid Aura∞ v6.12.7
                    </div>
                </div>
                <div className="text-right">
                    <div className="flex gap-2 justify-end mb-2">
                        <span className="bg-slate-100 text-slate-600 font-bold text-xs px-4 py-1.5 rounded-full border border-slate-200">
                            {day}
                        </span>
                        <span className="bg-slate-100 text-slate-600 font-bold text-xs px-4 py-1.5 rounded-full border border-slate-200">
                            {mode.toUpperCase()} MODE
                        </span>
                    </div>
                    <div className="text-base font-extrabold text-slate-700 uppercase tracking-wide">
                        {selectionInfo || 'ALL CLASSES'}
                    </div>
                </div>
            </div>

            {/* Slots Collection */}
            <div className="flex flex-col gap-4">
                {slots.map((slot, index) => (
                    <div key={index} className="print-slot-wrapper">
                        <ProcessSlotCard
                            slotData={slot}
                            index={index}
                            day={day}
                            isActive={false}
                            isPrintView={true}
                        />
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="mt-10 border-t border-slate-100 pt-4 flex justify-between text-[11px] text-slate-400 font-semibold">
                <div>https://luciduol.netlify.app</div>
                <div>{generatedAt}</div>
            </div>
        </div>
    );
}
