import React from 'react';
import { ProcessedSlot } from '@/lib/parser';

interface TimetablePrintViewProps {
    slots: ProcessedSlot[];
    day: string;
    room?: string;
    mode: 'student' | 'teacher' | 'room';
    date?: string;
    filters: any;
    generatedAt: string;
}

export default function TimetablePrintView({ slots, day, room, mode, date, filters, generatedAt }: TimetablePrintViewProps) {
    let selectionInfo = "";
    if (mode === 'student') {
        selectionInfo = `${filters.program || ''} ${filters.semester || ''} ${filters.section || ''}`.trim();
        if (filters.course) selectionInfo += ` (${filters.course})`;
    } else if (mode === 'teacher') {
        selectionInfo = filters.teacherName || "";
        if (filters.course) selectionInfo += ` (${filters.course})`;
    } else if (mode === 'room') {
        selectionInfo = filters.roomNumber || "";
    }

    const getAccent = (isLab: boolean, isFree: boolean) => {
        if (isFree) return { color: '#10b981', thin: 'rgba(16, 185, 129, 0.15)', bg: 'linear-gradient(135deg, #ecfdf5 0%, rgba(236,253,245,0.5) 50%, #ffffff 100%)', badgeColor: '', badgeBorder: '' };
        if (isLab) return { color: '#f59e0b', thin: 'rgba(245, 158, 11, 0.15)', bg: 'linear-gradient(135deg, #fffbeb 0%, rgba(255,251,235,0.5) 50%, #ffffff 100%)', badgeColor: '#92400e', badgeBorder: '#fcd34d' };
        return { color: '#6366f1', thin: 'rgba(99, 102, 241, 0.12)', bg: 'linear-gradient(135deg, #eef2ff 0%, rgba(238,242,255,0.5) 50%, #ffffff 100%)', badgeColor: '#4338ca', badgeBorder: '#c7d2fe' };
    };

    // Shared card wrapper with floating accent bar
    const SlotCard = ({ accent, children, minH }: { accent: ReturnType<typeof getAccent>, children: React.ReactNode, minH?: string }) => (
        <div style={{
            position: 'relative',
            background: accent.bg,
            borderRadius: '14px',
            padding: '18px 24px 18px 32px',
            borderTop: `1px solid ${accent.thin}`,
            borderRight: `1px solid ${accent.thin}`,
            borderBottom: `1px solid ${accent.thin}`,
            borderLeft: `1px solid ${accent.thin}`,
            minHeight: minH || 'auto',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
        }}>
            {/* Floating Accent Bar */}
            <div style={{
                position: 'absolute',
                left: '10px',
                top: '14px',
                bottom: '14px',
                width: '5px',
                borderRadius: '9999px',
                background: accent.color,
            }} />
            {children}
        </div>
    );

    return (
        <div id="timetable-print-view" style={{ width: '1220px', background: '#ffffff', padding: '40px', fontFamily: 'Inter, system-ui, sans-serif', color: '#1e293b' }}>
            {/* Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px', paddingBottom: '20px', borderBottom: '2px solid #e2e8f0' }}>
                <div>
                    <div style={{ fontSize: '28px', fontWeight: 900, color: '#334155', letterSpacing: '-1px' }}>
                        Lucid <span style={{ color: '#7c3aed' }}>Timetable</span>
                    </div>
                    <div style={{ fontSize: '11px', color: '#94a3b8', fontWeight: 600, marginTop: '2px' }}>
                        Generated by Lucid Aura∞ v6.11.3
                    </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                    <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end' }}>
                        <span style={{ background: '#f1f5f9', color: '#475569', fontWeight: 700, fontSize: '12px', padding: '6px 16px', borderRadius: '9999px', borderTop: '1px solid #e2e8f0', borderRight: '1px solid #e2e8f0', borderBottom: '1px solid #e2e8f0', borderLeft: '1px solid #e2e8f0' }}>{day}</span>
                        <span style={{ background: '#f1f5f9', color: '#475569', fontWeight: 700, fontSize: '12px', padding: '6px 16px', borderRadius: '9999px', borderTop: '1px solid #e2e8f0', borderRight: '1px solid #e2e8f0', borderBottom: '1px solid #e2e8f0', borderLeft: '1px solid #e2e8f0' }}>{mode.toUpperCase()} MODE</span>
                    </div>
                    <div style={{ fontSize: '16px', fontWeight: 800, color: '#334155', textAlign: 'right', marginTop: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>{selectionInfo || 'ALL CLASSES'}</div>
                </div>
            </div>

            {/* Slots */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                {slots.map((slot, idx) => {
                    const isFree = !slot.entries || slot.entries.length === 0;
                    const isLab = !isFree && slot.entries[0]?.isLab;
                    const accent = getAccent(isLab, isFree);

                    if (isFree) {
                        return (
                            <SlotCard key={idx} accent={accent} minH="90px">
                                <div style={{ fontSize: '11px', fontWeight: 700, color: '#b0b0b0', marginBottom: '6px' }}>{slot.time}</div>
                                <div style={{ color: '#10b981', fontSize: '22px', fontWeight: 900, letterSpacing: '0.25em', textTransform: 'uppercase', textAlign: 'center', width: '100%' }}>FREE</div>
                            </SlotCard>
                        );
                    }

                    return (
                        <SlotCard key={idx} accent={accent}>
                            {slot.entries.map((entry, ei) => (
                                <div key={ei}>
                                    {ei > 0 && <hr style={{ borderTop: '1px solid rgba(0,0,0,0.06)', borderRight: 'none', borderBottom: 'none', borderLeft: 'none', margin: '14px 0' }} />}
                                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                        <div style={{ flex: 1 }}>
                                            <div style={{ fontSize: '11px', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '6px' }}>
                                                <span style={{ color: '#a78bfa' }}>TIME:</span>{'  '}
                                                <span style={{ color: '#64748b', fontWeight: 700 }}>{slot.time}</span>
                                            </div>
                                            <div style={{ fontSize: '17px', fontWeight: 900, color: '#1e293b', marginBottom: '3px', lineHeight: '1.25', letterSpacing: '-0.01em' }}>{entry.course || 'Untitled'}</div>
                                            <div style={{ fontSize: '13px', fontWeight: 600, color: '#94a3b8' }}>{entry.instructor || 'Staff'}</div>
                                        </div>
                                        <div style={{ textAlign: 'right', flexShrink: 0, display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '4px' }}>
                                            <div style={{
                                                background: '#fff',
                                                color: accent.badgeColor,
                                                fontSize: '9px',
                                                fontWeight: 900,
                                                padding: '4px 14px',
                                                borderRadius: '9999px',
                                                borderTop: `1.5px solid ${accent.badgeBorder}`,
                                                borderRight: `1.5px solid ${accent.badgeBorder}`,
                                                borderBottom: `1.5px solid ${accent.badgeBorder}`,
                                                borderLeft: `1.5px solid ${accent.badgeBorder}`,
                                                letterSpacing: '0.06em',
                                                textTransform: 'uppercase',
                                            }}>
                                                {entry.isLab ? 'LABORATORY' : 'LECTURE'}
                                            </div>
                                            <div style={{ fontSize: '12px', color: '#94a3b8', fontWeight: 700 }}>
                                                Room <span style={{ color: '#1e293b', fontWeight: 900 }}>{entry.room}</span>
                                            </div>
                                            <div style={{ fontSize: '11px', fontWeight: 800, color: '#64748b', letterSpacing: '0.02em', textTransform: 'uppercase' }}>{entry.class}</div>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </SlotCard>
                    );
                })}
            </div>

            {/* Footer */}
            <div style={{ marginTop: '40px', borderTop: '1px solid #f1f5f9', paddingTop: '16px', display: 'flex', justifyContent: 'space-between', fontSize: '11px', color: '#c0c0c0', fontWeight: 600 }}>
                <div>https://luciduol.netlify.app</div>
                <div>{generatedAt}</div>
            </div>
        </div>
    );
}
